[project]
name = "ygo-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "graspologic>=3.4.4",
    "llama-index>=0.13.3",
    "llama-index-graph-stores-neo4j>=0.5.1",
    "llama-index-llms-azure-openai>=0.4.1",
    "llama-index-utils-workflow>=0.4.1",
]
