from enum import Enum


class Race(str, Enum):
    Aqua = "Aqua"
    Beast = "Beast"
    Beast_Warrior = "Beast-Warrior"
    Creator_God = "Creator-God"
    Cyberse = "Cyberse"
    Dinosaur = "Dinosaur"
    Divine_Beast = "Divine-Beast"
    Dragon = "Dragon"
    Fairy = "Fairy"
    Fiend = "Fiend"
    Fish = "Fish"
    Insect = "Insect"
    Machine = "Machine"
    Plant = "Plant"
    Psychic = "Psychic"
    Pyro = "Pyro"
    Reptile = "Reptile"
    Rock = "Rock"
    Sea_Serpent = "Sea Serpent"
    Spellcaster = "Spellcaster"
    Thunder = "Thunder"
    Warrior = "Warrior"
    Winged_Beast = "Winged Beast"
    Wyrm = "Wyrm"
    Zombie = "Zombie"